#!/bin/zsh
set -euo pipefail

AIUSAGEMETER_SCRIPT_DIR=${0:A:h}
AIUSAGEMETER_ROOT=${AIUSAGEMETER_SCRIPT_DIR:h}
AIUSAGEMETER_APP="$AIUSAGEMETER_ROOT/dist/AIUsageMeter.app"
AIUSAGEMETER_CAPTURE=${1:-"$AIUSAGEMETER_ROOT/docs/aiusagemeter-demo.png"}

mkdir -p "${AIUSAGEMETER_CAPTURE:h}"
AIUSAGEMETER_DEMO=1 AIUSAGEMETER_DEMO_EXPANDED=${AIUSAGEMETER_DEMO_EXPANDED:-1} AIUSAGEMETER_SNAPSHOT_PATH="$AIUSAGEMETER_CAPTURE" AIUSAGEMETER_EXIT_AFTER_SNAPSHOT=1 "$AIUSAGEMETER_APP/Contents/MacOS/AIUsageMeter" &
AIUSAGEMETER_PID=$!
trap 'kill "$AIUSAGEMETER_PID" 2>/dev/null || true' EXIT INT TERM
wait "$AIUSAGEMETER_PID" 2>/dev/null || true
trap - EXIT INT TERM
test -s "$AIUSAGEMETER_CAPTURE"
echo "Captured $AIUSAGEMETER_CAPTURE"
