#!/bin/zsh
set -euo pipefail

USAGEMETER_SCRIPT_DIR=${0:A:h}
USAGEMETER_ROOT=${USAGEMETER_SCRIPT_DIR:h}
USAGEMETER_APP="$USAGEMETER_ROOT/dist/UsageMeter.app"
USAGEMETER_CAPTURE="$USAGEMETER_ROOT/docs/usagemeter-demo.png"

mkdir -p "$USAGEMETER_ROOT/docs"
USAGEMETER_DEMO=1 USAGEMETER_DEMO_EXPANDED=1 USAGEMETER_SNAPSHOT_PATH="$USAGEMETER_CAPTURE" USAGEMETER_EXIT_AFTER_SNAPSHOT=1 "$USAGEMETER_APP/Contents/MacOS/UsageMeter" &
USAGEMETER_PID=$!
trap 'kill "$USAGEMETER_PID" 2>/dev/null || true' EXIT INT TERM
wait "$USAGEMETER_PID" 2>/dev/null || true
trap - EXIT INT TERM
test -s "$USAGEMETER_CAPTURE"
echo "Captured $USAGEMETER_CAPTURE"
